server:
  port:
    9292
#  servlet:
#    context-path: /payment-service

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices-payment-service
    username: postgres
    password: Dhanesh
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: Payment_consumer_group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.dw.paymentservice.dto


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
